### ISSUE TITLE
intersection of convex polygons sometime works fine and sometime fails

### ISSUE THREAD

**Issue by kleinerl** [GouMinghao/Geometry3D#10]
Hi
Thank you for the beautiful library.

When I run this code:
from Geometry3D import *

poly1=Sphere(Point(15.592607258702628, -66.15776443481445, 32.0),10,n1=7,n2=3)
poly2=Cylinder(Point(229.78870794537943, -64.86530276807025, 32.0),10,Vector(Point(229.78870794537943, -64.86530276807025, 32.0),Point(214.4889864671277, -64.95762145752087, 32.0)),10)

print(intersection(poly1,poly2))

I get the following output options:
* ValueError: Convex Check Fails Because Point(17.840763238923472, -70.82610843057509, 23.521216889812855) Is Not On Plane(Point(15.592607250905829, -66.1577644285967, 22.000000002672117), Vector(0.0018647292618591013, -0.30901128616936524, -0.9510565429062221))
* ValueError: Convex Check Fails Because Point(13.34985261467274, -70.81489244040448, 23.508768079903675) Is Not On Plane(Point(15.59260723547124, -66.15776444011686, 22.000000006384916), Vector(-0.0018645713266517239, 0.3090114447166194, 0.9510564917016842))
* ValueError: Convex Check Fails Because Point(15.59260723547124, -66.15776444011686, 22.000000006384916) Is Not On Plane(Point(17.840763238923472, -70.82610843057509, 23.521216889812855), Vector(0.0018645699754517861, -0.30901136992221073, -0.9510565160060707))
* None

It's strange, but the geometrical objects not even close:
![Figure_1](https://user-images.githubusercontent.com/13328405/147873889-30faf92b-d817-483a-94b9-f529deab835f.jpg)

Please, help

**Comment by GouMinghao** [comment]
Thank you for your bug report, this is a problem of floating point precision. 
A quick fix would be add `set_eps(1e-5)` after importing `Geometry3D`.

This problem will be fixed in future version.
