### ISSUE TITLE
Bug in ConvexPolygon-Plane intersection

### ISSUE THREAD

**Issue by ThomasCassimon** [GouMinghao/Geometry3D#11]
There is currently a bug in the code for ConvexPolygon-Plane Intersection.
This bug is caused by a minor typo, and can be fixed relatively easily.

If you look at[ line 98-101 in "Geometry3D/calc/intersection.py"](https://github.com/GouMinghao/Geometry3D/blob/master/Geometry3D/calc/intersection.py#L98), you'll find this code:

```
    elif isinstance(a, Plane) and isinstance(b, ConvexPolygon):
        return inter_plane_convexpolygon(a,b)
    elif isinstance(a, ConvexPolygon) and isinstance(a, Plane):
        return inter_plane_convexpolygon(b,a)
```

In the second `elif` statement, you can see that we are checking the type of `a` twice, without checking the type of `b`.

This should be changed to the following:
```
    elif isinstance(a, Plane) and isinstance(b, ConvexPolygon):
        return inter_plane_convexpolygon(a,b)
    elif isinstance(a, ConvexPolygon) and isinstance(b, Plane):
        return inter_plane_convexpolygon(b,a)
```

Until then, the work-around is to simply always specify the `Plane` first, and the `ConvexPolygon` second, so that you trigger the first `elif`, rather than the second.

Thanks in advance!

**Comment by GouMinghao** [comment]
Thank you for your great bug report which is difficult for me to find.
Your suggestion will be merged in the soon fix.
