### ISSUE TITLE
maybe a bug

### ISSUE THREAD

**Issue by yfismine** [GouMinghao/Geometry3D#14]
When I execute the code below the program has an error

```python
from Geometry3D import *
circle = Circle(Point(503.967529, 0, 370.521179),y_unit_vector(),400)
segment = Segment(Point(-353.2565, 0, -68.26225), Point(721.19, 0, 477.95))
print(circle.intersection(segment))
```
Hope you can tell me what is causing this problem
![image](https://user-images.githubusercontent.com/53209596/192302001-671115a7-8adb-46aa-93f2-541927985cc4.png)

**Comment by yfismine** [comment]
Seems to be a precision issue

**Comment by GouMinghao** [comment]
Precision problem is a known problem, it might be solved in the next version
